# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

#  config.vm.provider "virtualbox" do |v|
#    v.gui = true
#  end
  config.ssh.forward_x11 = "true"
 
  config.vm.define("kali") do |kali_config|
    kali_config.vm.box = "kali"
    kali_config.vm.guest = "debian"
    kali_config.vm.box_url = "https://ccdc:ccDC34UtpAgu@boxes.cs.ucr.edu/ccdc/kali/kali-2-amd64-virtualbox.box"
    kali_config.vm.box_download_checksum = "83132dabfdbe15b44ab5883fddf6c195"
    kali_config.vm.box_download_checksum_type = "md5"
    kali_config.vm.network "private_network", ip: "192.168.99.130", netmask: "255.255.255.0"
  end

  config.vm.define("metasploitable") do |metasploitable_config|
    metasploitable_config.vm.box = "metasploitable"
    metasploitable_config.vm.box_url = "https://ccdc:ccDC34UtpAgu@boxes.cs.ucr.edu/ccdc/metasploitable/metasploitable2-virtualbox.box"
    metasploitable_config.vm.box_download_checksum = "079d88798a11c33651293fd957206bc5"
    metasploitable_config.vm.box_download_checksum_type = "md5"
    metasploitable_config.vm.network "private_network", ip: "192.168.99.131", netmask: "255.255.255.0"
    metasploitable_config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1", auto_correct: true
  end

end 

